version: '3.9'
services:
  db:
    image: mysql:5.7
    volumes: 
    - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
    - "13306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
      
  app:
    image: node:14
    volumes: 
    - ./my-app:/app
    ports:
    - "3000:3000"
    working_dir: /app
    command: npm run dev
    environment: 
    - CHOKIDAR_USEPOLLING=true
    restart: always

