version: '3.9'
services:
  db:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes: 
    - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
    - "8080:8080"
    restart: always
      
  app:
    image: node:14
    volumes: 
    - ./my-app:/app
    ports:
    - "3000:3000"
    restart: always
    working_dir: /app
    command: npm run dev
    environment: 
    - CHOKIDAR_USEPOLLING=true

